### ISSUE TITLE
panic: Get /feeds/json/cve/1.1/nvdcve-1.1-2021.meta: unsupported protocol scheme

### ISSUE THREAD

**Issue by aoberest** [patsevanton/nist_data_mirror_golang#1]
Hello,
i have some problem.
Service `nist-data-mirror.service ` won't start.

```
# /usr/bin/nist-data-mirror

Download nvdcve-1.1-modified.meta from /feeds/json/cve/1.1/nvdcve-1.1-modified.meta
file /var/www/repos/nist-data-mirror/nvdcve-1.1-modified.meta exist 
Download nvdcve-1.1-modified.json.gz from /feeds/json/cve/1.1/nvdcve-1.1-modified.json.gz
file /var/www/repos/nist-data-mirror/nvdcve-1.1-modified.json.gz exist 
Download nvdcve-1.1-modified.json.zip from /feeds/json/cve/1.1/nvdcve-1.1-modified.json.zip
file /var/www/repos/nist-data-mirror/nvdcve-1.1-modified.json.zip exist 
Download nvdcve-1.1-recent.meta from /feeds/json/cve/1.1/nvdcve-1.1-recent.meta
file /var/www/repos/nist-data-mirror/nvdcve-1.1-recent.meta exist 
Download nvdcve-1.1-recent.json.gz from /feeds/json/cve/1.1/nvdcve-1.1-recent.json.gz
file /var/www/repos/nist-data-mirror/nvdcve-1.1-recent.json.gz exist 
Download nvdcve-1.1-recent.json.zip from /feeds/json/cve/1.1/nvdcve-1.1-recent.json.zip
file /var/www/repos/nist-data-mirror/nvdcve-1.1-recent.json.zip exist 
Download nvdcve-1.1-2021.meta from /feeds/json/cve/1.1/nvdcve-1.1-2021.meta
panic: Get /feeds/json/cve/1.1/nvdcve-1.1-2021.meta: unsupported protocol scheme ""

goroutine 1 [running]:
main.periodicFunction(0xc000373800, 0x42, 0x80)
	/builddir/build/BUILD/_build/src/github.com/patsevanton/nist_data_mirror_golang/main.go:30 +0x341
main.main()
	/builddir/build/BUILD/_build/src/github.com/patsevanton/nist_data_mirror_golang/main.go:18 +0x67
You have mail in /var/spool/mail/root
```

Could you please tell me what is mean ?

**Comment by patsevanton** [comment]
**ERR_TOO_MANY_REDIRECTS** when open https://nvd.nist.gov/feeds/json/cve/1.1
need refactored.

**Comment by patsevanton** [comment]
Fix by commit https://github.com/patsevanton/nist_data_mirror_golang/commit/236e5b6dcb89ddd9a8b9b77a33f96937e1d02aa0
